const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class GlobalSearchPanel {
  constructor({root,engine,stateManager,bus}={}){this.root=root;this.engine=engine;this.state=stateManager;this.bus=bus;this.results=[];this.index=0;this.trigger=document.createElement('button');this.trigger.type='button';this.trigger.className='wi-search-trigger';this.trigger.innerHTML='<span>⌕</span> SEARCH <kbd>CTRL K</kbd>';root?.append(this.trigger);this.el=document.createElement('div');this.el.className='wi-search';this.el.hidden=true;this.el.innerHTML=`<div class="wi-search-backdrop" data-search="close"></div><section class="wi-search-card" role="dialog" aria-modal="true" aria-label="Recherche globale"><header><span>GLOBAL SEARCH</span><kbd>CTRL K</kbd></header><input type="search" autocomplete="off" spellcheck="false" placeholder="France, Marseille, Suez, oil, blocked routes…" data-search-input><div class="wi-search-results" data-search-results></div><footer>↑↓ SELECT · ENTER LOCATE · ESC CLOSE</footer></section>`;root?.append(this.el);this.input=this.el.querySelector('[data-search-input]');this.list=this.el.querySelector('[data-search-results]');this.bind();this.trigger.addEventListener('click',()=>this.open());}
  bind(){this.el.querySelector('[data-search="close"]').addEventListener('click',()=>this.close());this.input.addEventListener('input',()=>this.refresh());this.input.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();this.close();}else if(e.key==='ArrowDown'){e.preventDefault();this.index=Math.min(this.results.length-1,this.index+1);this.render();}else if(e.key==='ArrowUp'){e.preventDefault();this.index=Math.max(0,this.index-1);this.render();}else if(e.key==='Enter'){e.preventDefault();this.activate(this.index);}});this.list.addEventListener('click',e=>{const row=e.target.closest('[data-search-index]');if(row)this.activate(Number(row.dataset.searchIndex));});}
  open(query=''){this.el.hidden=false;this.state.patch({search:{open:true,query,selectedIndex:0}},'search:open');this.input.value=query;this.refresh();requestAnimationFrame(()=>this.input.focus());}
  close(){this.el.hidden=true;this.state.patch({search:{open:false,query:'',selectedIndex:0}},'search:close');}
  refresh(){this.index=0;this.results=this.engine.search(this.input.value,{limit:14});this.state.patch({search:{open:true,query:this.input.value,selectedIndex:0}},'search:query');this.render();}
  render(){this.state.patch({search:{selectedIndex:this.index}},'search:index');this.list.innerHTML=this.results.length?this.results.map((r,i)=>`<button type="button" data-search-index="${i}" class="${i===this.index?'is-active':''}"><span>${esc(r.kind)}</span><div><b>${esc(r.title)}</b><small>${esc(r.subtitle)}</small></div><em>↗</em></button>`).join(''):'<p>NO RESULT</p>';this.list.querySelector('.is-active')?.scrollIntoView?.({block:'nearest'});}
  activate(index){const result=this.results[index];if(!result)return;this.engine.activate(result);this.close();}
  destroy(){this.trigger.remove();this.el.remove();}
}
