export class InfrastructureInteraction {
  constructor({canvas,stateManager,infrastructureGraph,renderer,routeRenderer=null,mobileRenderer=null,routeEngine=null,trafficEngine=null,layerManager,bus,clusterManager=null,mapCamera=null,selectionContext=null,focusEngine=null}){
    this.canvas=canvas;this.state=stateManager;this.graph=infrastructureGraph;this.renderer=renderer;this.routeRenderer=routeRenderer;this.mobileRenderer=mobileRenderer;this.routes=routeEngine;this.traffic=trafficEngine;this.layers=layerManager;this.bus=bus;this.clusters=clusterManager;this.mapCamera=mapCamera;this.selection=selectionContext;this.focus=focusEngine;
    for(const n of ['onMove','onClick','onLeave','onDoubleClick'])this[n]=this[n].bind(this);
  }
  init(){this.canvas.addEventListener('pointermove',this.onMove);this.canvas.addEventListener('click',this.onClick,true);this.canvas.addEventListener('dblclick',this.onDoubleClick,true);this.canvas.addEventListener('pointerleave',this.onLeave);}
  active(){const s=this.state.get();return !s.transition.active&&(s.view==='WORLD'||s.view==='COUNTRY');}
  coords(e){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
  pick(e){const p=this.coords(e);return this.mobileRenderer?.pick(p.x,p.y)||this.renderer?.pick(p.x,p.y)||this.routeRenderer?.pick(p.x,p.y)||null;}
  onMove(e){if(!this.active())return;const hit=this.pick(e);this.canvas.style.cursor=hit?'pointer':'grab';this.state.setHoveredInfrastructure(hit?.kind==='infrastructure'?hit.id:null);}
  onLeave(){if(this.active()){this.canvas.style.cursor='default';this.state.setHoveredInfrastructure(null);}}
  applyAuto(hit){if(!hit)return;if(hit.kind==='infrastructure'){const node=this.graph.get(hit.id);if(node)this.layers.enableAutoFor(node.type);}else if(hit.kind==='vehicle'){const v=this.traffic?.get(hit.id);if(v)this.layers.enableAutoFor(v.type);}else if(hit.kind==='route'){const r=this.routes?.get(hit.id);if(r)this.layers.enableAutoFor(r.type==='SEA_ROUTE'?'SHIP':r.type==='AIR_ROUTE'?'PLANE':r.type==='RAIL_ROUTE'?'TRAIN':'TRUCK');}}
  selectHit(hit){if(!hit)return false;if(hit.kind==='cluster'){const cluster=hit.cluster||this.clusters?.get(hit.id);const bounds=this.clusters?.bounds(cluster);if(bounds)this.mapCamera?.fitBounds(bounds,{padding:.22});return true;}this.applyAuto(hit);if(hit.kind==='infrastructure'){if(this.selection)this.selection.select('INFRASTRUCTURE',hit.id,{autoLayers:false,record:true});else{this.state.setSelectedInfrastructure(hit.id);this.state.setSelectedRoute(null);this.state.setSelectedVehicle(null);}}else if(hit.kind==='vehicle'){if(this.selection)this.selection.select('VEHICLE',hit.id,{autoLayers:false,record:true});else{this.state.setSelectedInfrastructure(null);this.state.setSelectedRoute(null);this.state.setSelectedVehicle(hit.id);}}else if(hit.kind==='route'){if(this.selection)this.selection.select('ROUTE',hit.id,{autoLayers:false,record:true});else{this.state.setSelectedInfrastructure(null);this.state.setSelectedVehicle(null);this.state.setSelectedRoute(hit.id);}}return true;}
  onClick(e){if(!this.active()||Date.now()<Number(this.canvas.dataset.mapDragSuppressUntil||0))return;const hit=this.pick(e);if(!hit)return;if(this.selectHit(hit)){e.preventDefault();e.stopImmediatePropagation();}}
  onDoubleClick(e){if(!this.active()||Date.now()<Number(this.canvas.dataset.mapDragSuppressUntil||0))return;const hit=this.pick(e);if(!hit)return;if(hit.kind==='cluster'){this.selectHit(hit);}else{this.selectHit(hit);this.focus?.set(hit.kind==='infrastructure'?'INFRASTRUCTURE':hit.kind==='vehicle'?'VEHICLE':'ROUTE',hit.id);if(hit.kind==='infrastructure'){const n=this.graph.get(hit.id);if(n)this.mapCamera?.focus(n.position);}else if(hit.kind==='vehicle'){const v=this.traffic?.get(hit.id);if(v?.position)this.mapCamera?.focus(v.position);}else if(hit.kind==='route'){const r=this.routes?.get(hit.id);if(r){const lons=r.points.map(p=>p.lon),lats=r.points.map(p=>p.lat);this.mapCamera?.fitBounds([Math.min(...lons),Math.min(...lats),Math.max(...lons),Math.max(...lats)],{padding:.18});}}}e.preventDefault();e.stopImmediatePropagation();}
  destroy(){this.canvas.removeEventListener('pointermove',this.onMove);this.canvas.removeEventListener('click',this.onClick,true);this.canvas.removeEventListener('dblclick',this.onDoubleClick,true);this.canvas.removeEventListener('pointerleave',this.onLeave);}
}
