import { LabelManager } from '../map/LabelManager.js';
import { VisualPriorityManager } from '../map/VisualPriorityManager.js';
const STATUS_ALPHA={OPERATIONAL:1,DEGRADED:.82,DISRUPTED:.66,CRITICAL:.52,OFFLINE:.32,DESTROYED:.16};
const FALLBACK={CAPITAL:'★',CITY:'●',PORT:'⚓',AIRPORT:'✈',AIRBASE:'✈',NAVAL_BASE:'⚓',INDUSTRY:'⚙',POWER_PLANT:'⚡',POWER_GRID:'⌁',REFINERY:'◆',LOGISTICS_HUB:'▰',DATACENTER:'▣',IXP:'◇',CABLE_LANDING:'◉',RADAR:'⌁',ARSENAL:'▦',PIPELINE_NODE:'═',MINE:'◆',DAM:'▥',BRIDGE:'═',CHOKEPOINT:'◈',SPACEPORT:'▲',GROUND_STATION:'⌁',MILITARY_BASE:'▣',RAIL_HUB:'▤',HOSPITAL:'✚',HEALTH:'✚',ROAD_HUB:'⬡',ENERGY_STORAGE:'◆',COMMAND_CENTER:'▣'};
export class InfrastructureRenderer {
  constructor(){this.images=new Map();this.loading=new Set();this.hitboxes=[];this.labels=new LabelManager();this.priority=new VisualPriorityManager();}
  image(path){if(!path||typeof Image==='undefined')return null;if(this.images.has(path))return this.images.get(path);if(this.loading.has(path))return null;this.loading.add(path);const img=new Image();img.decoding='async';img.onload=()=>{this.images.set(path,img);this.loading.delete(path);};img.onerror=()=>this.loading.delete(path);img.src=path;return null;}
  focusAlpha(focus,id){if(!focus?.active)return 1;if(focus.type==='INFRASTRUCTURE'&&focus.id===id)return 1;return focus.nodeIds?.includes(id)?.72:.15;}
  renderCluster(ctx,cluster,{alpha=1,mode='world'}){const size=mode==='country'?19:15;ctx.save();ctx.globalAlpha=alpha*.9;ctx.translate(cluster.x,cluster.y);ctx.fillStyle='rgba(0,20,29,.92)';ctx.strokeStyle='rgba(0,234,255,.68)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,size,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='rgba(223,252,255,.98)';ctx.font=`700 ${mode==='country'?13:12}px ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(cluster.count),0,0);ctx.restore();this.hitboxes.push({kind:'cluster',id:cluster.id,cluster,x:cluster.x,y:cluster.y,r:size+5});}
  render(ctx,items,projection,{alpha=1,mode='world',selectedId=null,time=0,zoom=1,focus=null,maxLabels=90}={}){
    this.hitboxes=[];const base=mode==='country'?27:mode==='world'?18:13;const labels=[];
    for(const item of items){if(item?.isCluster){this.renderCluster(ctx,item,{alpha,mode});continue;}const node=item;const p=projection.project(node.position.lat,node.position.lon);if(!p?.visible)continue;const statusAlpha=STATUS_ALPHA[node.status]??.8,selected=node.id===selectedId;const focusA=this.focusAlpha(focus,node.id);const size=base*(.84+node.strategicValue*.42)*(selected?1.18:1);ctx.save();ctx.globalAlpha=alpha*statusAlpha*focusA;const pulse=selected?1+Math.sin(time*4)*.08:1;ctx.translate(p.x,p.y);ctx.scale(pulse,pulse);if(selected){ctx.beginPath();ctx.arc(0,0,size*.72,0,Math.PI*2);ctx.strokeStyle='rgba(0,234,255,.78)';ctx.lineWidth=1;ctx.stroke();}const img=this.image(node.icon);if(img?.complete&&img.naturalWidth){const ratio=img.naturalWidth/img.naturalHeight;let w=size,h=size;if(ratio>1)h=size/ratio;else w=size*ratio;ctx.globalAlpha*=.92;ctx.drawImage(img,-w/2,-h/2,w,h);}else{ctx.fillStyle=selected?'rgba(223,252,255,.98)':'rgba(0,234,255,.86)';ctx.shadowColor='rgba(0,234,255,.65)';ctx.shadowBlur=8;ctx.font=`600 ${Math.max(12,size*.66)}px ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(FALLBACK[node.type]||'◇',0,0);}ctx.restore();
      const priority=this.priority.priority(node,{selectedId});const show=selected||mode==='country'||zoom>=1.8||priority>=500;if(show)labels.push({text:node.name,x:p.x,y:p.y+size*.55+3,priority:priority+(selected?500:0),alpha:alpha*Math.max(.35,focusA),font:selected?'700 14px ui-monospace,monospace':'600 12px ui-monospace,monospace'});
      this.hitboxes.push({kind:'infrastructure',id:node.id,x:p.x,y:p.y,r:Math.max(9,size*.7)});
    }
    this.labels.draw(ctx,labels,{maxLabels});
  }
  pick(x,y){let best=null,bestD=Infinity;for(const h of this.hitboxes){const d=Math.hypot(x-h.x,y-h.y);if(d<=h.r&&d<bestD){best=h;bestD=d;}}return best;}
}
