const STYLE={SEA_ROUTE:['rgba(0,210,255,.22)',[7,7]],AIR_ROUTE:['rgba(142,247,255,.18)',[3,6]],ROAD_ROUTE:['rgba(95,221,204,.14)',[2,5]],RAIL_ROUTE:['rgba(223,252,255,.20)',[8,4]],PIPELINE_ROUTE:['rgba(255,190,90,.20)',[10,5]],DIGITAL_ROUTE:['rgba(167,116,255,.22)',[2,4]],ORBITAL_ROUTE:['rgba(0,234,255,.18)',[1,7]]};
const STATUS={OPEN:1,CONGESTED:.9,RESTRICTED:.68,RISKY:.78,BLOCKED:.42,CLOSED:.18};
const distanceToSegment=(px,py,ax,ay,bx,by)=>{const dx=bx-ax,dy=by-ay,l2=dx*dx+dy*dy;if(!l2)return Math.hypot(px-ax,py-ay);let t=((px-ax)*dx+(py-ay)*dy)/l2;t=Math.max(0,Math.min(1,t));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy));};
export class RouteNetworkRenderer {
  constructor(){this.hitboxes=[];}
  focusAlpha(focus,id){if(!focus?.active)return 1;if(focus.type==='ROUTE'&&focus.id===id)return 1;return focus.routeIds?.includes(id)?.8:.15;}
  render(ctx,routes,projection,{alpha=1,mode='world',selectedRouteId=null,focus=null}={}){this.hitboxes=[];for(const route of routes){const style=STYLE[route.type]||STYLE.SEA_ROUTE,selected=route.id===selectedRouteId;const effectiveStatus=(route.status==='OPEN'&&(route.congestionRuntime??route.congestion??0)>.82)?'CONGESTED':route.status;const statusA=STATUS[effectiveStatus]??1;ctx.save();ctx.globalAlpha=alpha*(selected?1:.78)*statusA*this.focusAlpha(focus,route.id);ctx.strokeStyle=selected?'rgba(223,252,255,.88)':effectiveStatus==='BLOCKED'||effectiveStatus==='CLOSED'?'rgba(255,92,92,.38)':route.status==='REROUTING'?'rgba(255,190,90,.62)':style[0];ctx.lineWidth=selected?1.8:(mode==='country'?1.05:.72);ctx.setLineDash(effectiveStatus==='BLOCKED'||effectiveStatus==='CLOSED'?[2,8]:style[1]);ctx.beginPath();let started=false,prev=null;const segments=[];for(const geo of route.points){const p=projection.project(geo.lat,geo.lon);if(!p?.visible)continue;if(!started){ctx.moveTo(p.x,p.y);started=true;}else{ctx.lineTo(p.x,p.y);segments.push([prev,p]);}prev=p;}if(started)ctx.stroke();ctx.restore();this.hitboxes.push({kind:'route',id:route.id,segments,width:selected?8:5});}}
  pick(x,y){let best=null,bestD=Infinity;for(const h of this.hitboxes){for(const [a,b] of h.segments){const d=distanceToSegment(x,y,a.x,a.y,b.x,b.y);if(d<=h.width&&d<bestD){best=h;bestD=d;}}}return best;}
}
