const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
export class TimelineReplayEngine {
  constructor({gameEngine,stateManager,bus=null,causalityEngine=null}={}){this.game=gameEngine;this.state=stateManager;this.bus=bus;this.causality=causalityEngine;this.liveSpeed=null;this.replay=null;this.snapshots=[];this.maxSnapshots=12;}
  records(filter={}){const rows=this.game?.api?.getTimeline?.({limit:5000,...filter})||[];const {sinceDay=-Infinity,untilDay=Infinity,country=null,kind=null,category=null}=filter||{};return rows.filter(r=>(Number(r.day)||0)>=sinceDay&&(Number(r.day)||0)<=untilDay&&(!country||r.country===country||r.target===country)&&(!kind||r.kind===kind)&&(!category||r.category===category));}
  range(){const rows=this.records();const clock=this.game?.api?.getClock?.()||{day:0,date:null};const min=rows.length?Math.min(...rows.map(r=>Number(r.day)||0)):0;const max=Math.max(clock.day||0,...rows.map(r=>Number(r.day)||0));return {min,max,current:clock.day||0,date:clock.date};}
  pauseSimulation(){const clock=this.game?.api?.getClock?.();if(this.liveSpeed===null)this.liveSpeed=clock?.speed??1;this.game?.api?.pause?.();}
  setCursorDay(day,{selectNearest=true}={}){const range=this.range();const cursor=Math.round(Math.max(range.min,Math.min(range.max,Number(day)||0)));this.pauseSimulation();let selectedId=null;if(selectNearest){const rows=this.records({untilDay:cursor});selectedId=rows.at(-1)?.id||null;}const patch={timeline:{mode:'HISTORY',cursorDay:cursor,selectedId,replayId:null,replayProgress:0}};this.state.patch(patch,'timeline:cursor');this.bus?.emit?.('timeline:changed',{...patch.timeline,range});return patch.timeline;}
  select(id){const row=this.records().find(r=>r.id===id||r.eventId===id);if(!row)return false;this.pauseSimulation();const timeline={mode:'HISTORY',cursorDay:row.day,selectedId:row.id,replayId:null,replayProgress:0};this.state.patch({timeline},'timeline:select');this.bus?.emit?.('timeline:changed',{...timeline,row});return structuredClone(row);}
  eventSequence(ref){const rows=this.records();const root=rows.find(r=>r.id===ref||r.eventId===ref&&r.kind!=='RIPPLE')||rows.find(r=>r.id===ref);if(!root)return[];const eventId=root.eventId||root.id;return [root,...rows.filter(r=>r.eventId===eventId&&r.kind==='RIPPLE'&&r.id!==root.id)].sort((a,b)=>(a.day||0)-(b.day||0)||(a.details?.step||0)-(b.details?.step||0));}
  replayEvent(ref,{stepSeconds=.85}={}){const sequence=this.eventSequence(ref);if(!sequence.length)return false;this.pauseSimulation();this.replay={id:sequence[0].eventId||sequence[0].id,sequence,index:0,elapsed:0,stepSeconds:Math.max(.05,Number(stepSeconds)||.85),paused:false};const row=sequence[0];const timeline={mode:'REPLAY',cursorDay:row.day,selectedId:row.id,replayId:this.replay.id,replayProgress:sequence.length<=1?1:0};this.state.patch({timeline},'timeline:replay-start');this.causality?.analyze?.('EVENT',this.replay.id);this.bus?.emit?.('timeline:replay-step',{row,index:0,total:sequence.length});return structuredClone(this.replay);}
  toggleReplayPause(){if(!this.replay)return false;this.replay.paused=!this.replay.paused;this.bus?.emit?.('timeline:replay-pause',{paused:this.replay.paused});return this.replay.paused;}
  update(dt){if(!this.replay||this.replay.paused)return;this.replay.elapsed+=Math.max(0,Number(dt)||0);if(this.replay.elapsed<this.replay.stepSeconds)return;this.replay.elapsed=0;if(this.replay.index>=this.replay.sequence.length-1){this.replay=null;return;}this.replay.index++;const row=this.replay.sequence[this.replay.index];const progress=this.replay.sequence.length<=1?1:this.replay.index/(this.replay.sequence.length-1);this.state.patch({timeline:{mode:'REPLAY',cursorDay:row.day,selectedId:row.id,replayId:this.replay.id,replayProgress:clamp(progress)}},'timeline:replay-step');this.bus?.emit?.('timeline:replay-step',{row,index:this.replay.index,total:this.replay.sequence.length});}
  live(){this.replay=null;const restore=this.liveSpeed===null?1:this.liveSpeed;this.liveSpeed=null;this.game?.api?.setSpeed?.(restore);const clock=this.game?.api?.getClock?.();const timeline={mode:'LIVE',cursorDay:clock?.day??0,selectedId:null,replayId:null,replayProgress:0};this.state.patch({timeline},'timeline:live');this.bus?.emit?.('timeline:changed',timeline);return timeline;}
  createSnapshot(label='SNAPSHOT'){const snap={id:`SNAP-${Date.now()}-${this.snapshots.length+1}`,label:String(label||'SNAPSHOT').slice(0,64),createdAt:new Date().toISOString(),day:this.game?.api?.getClock?.().day??0,date:this.game?.api?.getClock?.().date??null,game:this.game?.snapshot?.()||null,mode:'READ_ONLY'};this.snapshots.push(snap);if(this.snapshots.length>this.maxSnapshots)this.snapshots.shift();this.bus?.emit?.('timeline:snapshot',{snapshot:{...snap,game:undefined}});return {...snap,game:undefined};}
  listSnapshots(){return this.snapshots.map(s=>({...s,game:undefined}));}
  openSnapshot(id){const snap=this.snapshots.find(s=>s.id===id);if(!snap)return false;this.setCursorDay(snap.day);this.bus?.emit?.('timeline:snapshot-open',{snapshot:{...snap,game:undefined}});return {...snap,game:undefined};}
  stateInfo(){return {timeline:structuredClone(this.state.get().timeline),range:this.range(),replay:this.replay?{id:this.replay.id,index:this.replay.index,total:this.replay.sequence.length,paused:this.replay.paused}:null,snapshots:this.listSnapshots()};}
}
